name: qaz_tracker
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_core:
    git:
      url: https://github.com/skykz/flutter_core.git
      ref: "v1.0.17"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  get_it: ^7.6.4
  dio: ^5.3.3
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  sizer: 2.0.15
  equatable: 2.0.5
  another_flushbar: ^1.12.30
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1
  
  # pull_to_refresh: 2.0.0
  flutter_charts: ^0.5.2

  # both should be enabled
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.0
  google_maps_flutter_platform_interface: ^2.8.0
  fl_chart: ^0.68.0

  url_launcher: ^6.3.0
  community_charts_flutter: ^1.0.1
  geolocator: ^12.0.0

  # not latest version, because of error non-constant super constructor
  # filter
  syncfusion_flutter_charts: ^26.1.42
  dropdown_button2: ^2.1.3

  # map dependencies
  pointer_interceptor: ^0.10.1+1
  custom_info_window: ^1.0.1
  google_maps_cluster_manager: ^3.1.0
  semicircle_indicator: ^1.1.1
  flutter_launcher_icons: "^0.13.1"
  bloc: ^8.1.4

dependency_overrides: 
  intl: 0.18.0

flutter_launcher_icons:
  # android: "launcher_icon"
  # ios: true
  # image_path: "assets/icon/icon.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "1024 1.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
